### ISSUE TITLE
优先简体中文 脚本已被从 Greasy Fork 中删除

### ISSUE THREAD

**Issue by chsbuffer** [Roger-WIN/greasemonkey-user-scripts#2]
`This script was deleted from Greasy Fork`
https://greasyfork.org/scripts/392621-%E4%BC%98%E5%85%88%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87/code/%E4%BC%98%E5%85%88%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87.js
https://greasyfork.org/zh-CN/scripts/392621-%E4%BC%98%E5%85%88%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87

建议替换脚本 require 为 JsDelivr GitHub 反代
https://cdn.jsdelivr.net/gh/Roger-WIN/greasemonkey-user-scripts@main/Chinese%20(Simplified)%20first/_common/language-first.js

**Comment by Roger-WIN** [comment]
所有涉及到的脚本会在近几天适配。

**Comment by Roger-WIN** [comment]
Fixed in https://github.com/Roger-WIN/greasemonkey-user-scripts/commit/b10c408e458139f53547037fdb188da602ec6e54.

**NOTE**: [文档](https://greasyfork.org/zh-CN/help/external-scripts)显示，Greasy Fork 仅支持 jsDelivr 特定 commit 的 GitHub 引用。
